services:
  tts-server:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: tts-server
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    # для docker-compose без swarm:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  telegram-bot:
    build:
      context: ./telegramServer
      dockerfile: go.Dockerfile
    container_name: telegram-bot
    depends_on:
      - tts-server
    restart: unless-stopped
    networks:
      - mynetwork
    environment:
      - TELEGRAM_TOKEN=7791869623:AAHnM-acFOCkDou9SRgRVlYfjcXg5XSOHwI
      - GRPC_SERVER_HOST=tts-server
      - GRPC_SERVER_PORT=50051

networks:
  mynetwork:
    driver: bridge
