// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: audio_processor.proto

package audio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioProcessor_ProcessContent_FullMethodName = "/audio_processing.v1.AudioProcessor/ProcessContent"
)

// AudioProcessorClient is the client API for AudioProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioProcessorClient interface {
	ProcessContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ProcessingResponse, error)
}

type audioProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioProcessorClient(cc grpc.ClientConnInterface) AudioProcessorClient {
	return &audioProcessorClient{cc}
}

func (c *audioProcessorClient) ProcessContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ProcessingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessingResponse)
	err := c.cc.Invoke(ctx, AudioProcessor_ProcessContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioProcessorServer is the server API for AudioProcessor service.
// All implementations must embed UnimplementedAudioProcessorServer
// for forward compatibility.
type AudioProcessorServer interface {
	ProcessContent(context.Context, *ContentRequest) (*ProcessingResponse, error)
	mustEmbedUnimplementedAudioProcessorServer()
}

// UnimplementedAudioProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioProcessorServer struct{}

func (UnimplementedAudioProcessorServer) ProcessContent(context.Context, *ContentRequest) (*ProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessContent not implemented")
}
func (UnimplementedAudioProcessorServer) mustEmbedUnimplementedAudioProcessorServer() {}
func (UnimplementedAudioProcessorServer) testEmbeddedByValue()                        {}

// UnsafeAudioProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioProcessorServer will
// result in compilation errors.
type UnsafeAudioProcessorServer interface {
	mustEmbedUnimplementedAudioProcessorServer()
}

func RegisterAudioProcessorServer(s grpc.ServiceRegistrar, srv AudioProcessorServer) {
	// If the following call pancis, it indicates UnimplementedAudioProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioProcessor_ServiceDesc, srv)
}

func _AudioProcessor_ProcessContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioProcessorServer).ProcessContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioProcessor_ProcessContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioProcessorServer).ProcessContent(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioProcessor_ServiceDesc is the grpc.ServiceDesc for AudioProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio_processing.v1.AudioProcessor",
	HandlerType: (*AudioProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessContent",
			Handler:    _AudioProcessor_ProcessContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio_processor.proto",
}
